exoort const ACTION_SET_FROM = 'SET_FROM';
exoort const ACTION_SET_TO = 'SET_TO';
exoort const ACTION_SET_IS_CITY_SELECTOR_VISIBLE = 'SET_IS_CITY_SELECTOR_VISIBLE'
exoort const ACTION_SET_CURRENT_SELECTING_LEFT_CITY = 'SET_CURRENT_SELECTING_LEFT_CITY';
exoort const ACTION_SET_CITY_DATA = 'SET_CITY_DATA';
exoort const ACTION_SET_isLoadingCityData = 'SET_IS_LOADING_CITY_DATA';
exoort const ACTION_SET_isDateSelectorVisible = 'SET_IS_DATE_SELECTOR_VISIBLE';
exoort const ACTION_SET_highSpeed = 'SET_HIGH_SPEED';